### ISSUE TITLE
ERROR No valid FOIs to supplied

### ISSUE THREAD

**Issue by ale07alvarez** [mdozmorov/genomerunner_web#1]
No valid FOIs to supplied error:
input data
chr15 77747190 77747191 rs7178572        
chr15 77747190 77747277 rs11633054 

Database version:	db_5.00_07-22-2015
Background:	1snp142common.bed.gz
Time:	2017-08-22 22:57:06
P-value statistical test:	chisquare
Jobname:	4oanyb2gjgramr53r2okswu8kblv5ny8
Strand:	both
% Score threshold:	%
Organism:	hg19

###LOG###
2017-08-22 18:57:07,944 INFO Enrichment analysis started for 4oanyb2gjgramr53r2okswu8kblv5ny8
2017-08-22 18:57:20,407 WARNING Number of SNPs in custom_foi.bed.gz < 5. Removing it from analysis.
2017-08-22 18:57:20,407 WARNING 2 out of 2 custom_foi.bed.gz SNPs are not a part of the background. P-value are unreliable. Please, include all SNPs in the background and re-run analysis.
2017-08-22 18:57:20,407 ERROR No valid FOIs to supplied

**Comment by mdozmorov** [comment]
The problem is two SBPs only. With less than five SNPs enrichment analysis cannot be run. The warning tells about that:
WARNING Number of SNPs in custom_foi.bed.gz < 5. Removing it from analysis.

Bottom line - add more SNPs.

**Comment by ale07alvarez** [comment]
okay that worked for regulatory features when I select the gwasCatalog annotations 
I also get an error :
A total of 1304 regulatory datasets are uploaded/selected (Maximum 1000 allowed). Please, use less regulatory datasets for analysis.

I have only selected (check marked) the gwasCatalog option.
Thanks

**Comment by mdozmorov** [comment]
Yes, we restricted the number of regulatory features (server limitations), and "gwascatalog" had >1000 studies. I'd recommend skipping it all together - this is a special analysis, requiring exact coordinate matching. If absolutely necessary, I'll try to find a workaround.
