### ISSUE TITLE
Genome build: GRCh37 or GRCh38?

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [mdozmorov/genomerunner_web#2]
Hi Mikhail,

Could you tell me where I can find the genome builds of E088 LNG.FET and E096 LNG in the roadmap cell types table?

Thanks,
Jiangyuan

**Comment by mdozmorov** [comment]
Hi Jiangyuan,

All human genome annotation data corresponds to hg19/GRCh37 genome build. It is likely that over the years Roadmap, and, certainly, ENCODE, released many new tracks, including those you mentioned. GenomeRunner project is nearing the end of life, I suggest to look for other tools. See if you can find your cells here http://mulinlab.tmu.edu.cn/epicoloc, or explore other tools at https://github.com/mdozmorov/genomerunner_web/wiki/Similar-tools
